#!/usr/bin/env php
<?php
require_once(dirname(__FILE__) . '/lib/phpbdd.php');

$testDir = './tests';

if ($handle = opendir($testDir)) {

	while (false !== ($entry = readdir($handle))) {
		if (preg_match("/.*\.php$/sim", $entry)) {
			require_once($testDir . '/' . $entry);
		}
	}
}

bdd_errors();
